Repository BuildForSDG/Team-087-Frontend, pull requests merged in 2020-06, with the labels that each got.

#29 fixing issues
  yarn.lock
Labels: enhancement

#31 chore: fix merge conflict
  src/App.js
Labels: bug

#32 Ch apply codacy fixes
  package.json
  public/index.html
  public/manifest.json
  src/App.js
  src/components/auth/Login.js
  src/components/auth/Signup.js
  src/helpers.js
  src/tests/Login.spec.js
  src/tests/Signup.spec.js
Labels: documentation, enhancement

#33 login-feature backend integration
  package.json
  src/App.js
  src/components/NotFound.jsx
  src/components/auth/Login.js
  src/components/auth/Signup.js
  src/helpers.js
  src/tests/Login.spec.js
Labels: enhancement

#35 add file for pushState support on netlify
  public/_redirects
Labels: enhancement

#37 major ui-overhaul and aesthetic improvements
  public/index.html
  src/App.js
  src/components/DashBoard.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/NotFound.jsx
  src/components/auth/Login.jsx
  src/components/auth/Signup.jsx
  src/components/auth/Verify.jsx
  src/components/users/Appointment.jsx
  src/components/users/List.jsx
  src/components/users/Profile.jsx
  src/components/users/Recommendation.jsx
  src/components/users/Review.jsx
Labels: enhancement

#38 chore: update project documentation
  README.md
  app.properties
  public/index.html
Labels: documentation

#39 chore: fix pagination issue on fetching appointments
  README.md
  src/components/Footer.jsx
  src/components/NotFound.jsx
  src/components/auth/Verify.jsx
  src/components/users/Appointment.jsx
  src/components/users/List.jsx
  src/components/users/Profile.jsx
  src/components/users/Recommendation.jsx
Labels: enhancement

#40 account-verification-issue-fix
  src/App.js
  src/components/Audit.jsx
  src/components/Header.jsx
  src/components/auth/Verify.jsx
  src/components/groups/List.jsx
  src/components/users/List.jsx
Labels: enhancement
